/**
    ----------------------------------------------------------------------
    Homework #1:
    -----------
        Guess the run-time output.
            - Read Through The Code Line By Line.
            - Execute Each Line.
            - What output is generated by this code?
    ----------------------------------------------------------------------
**/

// Library Include.
#include <iostream>
// Namespaces.
using namespace std;

// Driver Code.
int main()
{
    cout << "\n\nGuess the "
         << "output\n---\n";
    cout << 10 + 20 - 5 << endl;
    cout << "14/2"
         << "\n";
    cout << 17 - 10 << "\n";
    cout << endl;
    cout << "\nPractice Makes Perfect";
    cout << "The Way to get started is to stop Talking and start Doing";

    return 0;

    cout << "\n\nBye\n\n"; // Will not be executed after the return statement.

    /*  OUTPUT:

                Guess the output
                ---
                25
                14/2
                7

                Practuce Makes PerfectThe Way to get started is to stop Talking and start Doing
    */
}